;; coding-modes-boot.el

(defun jem-essentials-coding-modes|init ()
  (use-package csv-mode
    :ensure t
    :mode "\\.csv\\'")
  (use-package go-mode
    :ensure t
    :mode "\\.go\\'")
  (use-package haskell-mode
    :ensure t
    :mode "\\(\\.ghs\\'\\|\\.hsc\\'\\)")
  (use-package css-mode
    :ensure t
    :mode "\\.css\\'")
  (use-package sass-mode
    :ensure t
    :mode "\\.sass\\'")
  (use-package scss-mode
    :ensure t
    :mode "\\.scss\\'")
  (use-package python
    :ensure t
    :interpreter ("python" . python-mode)
    :mode "\\(\\.py\\'\\|^BUILD$\\)")
  (use-package web-mode
    :ensure t
    :mode "\\(\\.html\\'\\|\\.hbs\\'\\|\\.ejs\\'\\|\\.php\\'\\)")
  (use-package coffee-mode
    :ensure t
    :mode "\\(\\.coffee\\'\\|\\.iced\\'\\)")
  (use-package js2-mode
    :ensure t
    :mode "\\.js\\'")
  (use-package json-mode
    :ensure t
    :mode "\\.json$")
  (use-package lua-mode
    :ensure t
    :mode "\\.lua\\'")
  (use-package markdown-mode
    :ensure t
    :mode "\\(\\.markdown\\'\\|\\.md\\'\\)")
  (use-package ruby-mode
    :ensure t
    :interpreter "ruby"
    :mode "\\(\\(?:\\.rb\\|ru\\|rake\\|thor\\|jbuilder\\|gemspec\\|podspec\\|/\\(?:Gem\\|Rake\\|Cap\\|Thor\\|Vagrant\\|Guard\\|Pod\\)file\\)\\'\\|Puppetfile\\)")
  (use-package swift-mode
    :ensure t
    :mode "\\.swift\\'")
  (use-package typescript-mode
    :ensure t
    :mode "\\.ts\\'")
  (use-package yaml-mode
    :ensure t
    :mode "\\(\\.e?ya?ml$\\|//.\\(yml\\|yaml\\)\\'\\|Procfile\\'\\)"))
